[technote]
id = "DMTN-227"
series_id = "DMTN"
canonical_url = "https://dmtn-227.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-227"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Kian-Tat", family = "Lim"}
internal_id = "limk"
orcid = "https://orcid.org/0000-0002-6338-6516"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
