[technote]
id = "DMTN-227"
series_id = "DMTN"
canonical_url = "https://dmtn-227.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-227"
github_default_branch = "main"
date_created = 2022-04-18T19:11:27
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
doi = "10.71929/rubin/2586436"
[[technote.authors]]
name = {given = "Kian-Tat", family = "Lim"}
internal_id = "limk"
orcid = "https://orcid.org/0000-0002-6338-6516"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
[[technote.authors]]
name = {given = "William", family = "O'Mullane"}
internal_id = "omullanew"
orcid = "https://orcid.org/0000-0003-4141-6195"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
ror = "https://ror.org/048g3cy84"
